version: '3.7'

networks:
  ls_ls-net:
    driver: overlay
    external: true

services:
  debug-container:
    image: mikesir87/aws-cli:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - ls_ls-net
    environment:
      AWS_ACCESS_KEY_ID: 'foo'
      AWS_SECRET_ACCESS_KEY: 'bar'
    command: aws --endpoint=http://s3:4572 s3 mb s3://test-bucket