version: '3.7'

networks:
  image-processor-net:
    driver: overlay

volumes:
  mysql-data:

services:
  image-processor-app-v0:
    image: sridharangopal/imageprocessor.rpi:latest
    networks:
      - image-processor-net
    depends_on:
      - image-processor-db
    ports:
      - '8080:8080'
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role != manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 0s

  image-processor-db:
    image: tobi312/rpi-mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_DATABASE: 'imagerepo'
      TZ: 'America/New_York'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'SuperS3cretPassword'
      MYSQL_ROOT_PASSWORD: 'SuperS3cretPassword'
    ports:
      - '3306:3306'
    networks:
      - image-processor-net
    volumes:
      - mysql-data:/var/lib/mysql
