version: '3.7'

networks:
  ls_ls-net:
    driver: overlay
    external: true
#  image-processor-net:
#    driver: overlay

volumes:
  mysql-data:

services:
  image-processor-app-v0:
#    image: sridharangopal/imageprocessor.rpi:latest
    image: ${APP_IMAGE}
    networks:
#      - image-processor-net
      - ls_ls-net
    depends_on:
      - image-processor-db
    ports:
      - '8080:8080'
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 0s

  image-processor-db:
#    image: hypriot/rpi-mysql
    image: ${DB_IMAGE}
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_DATABASE: 'imagerepo'
      TZ: 'America/New_York'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'SuperS3cretPassword'
      MYSQL_ROOT_PASSWORD: 'SuperS3cretPassword'
    ports:
      - '3306:3306'
    networks:
#      - image-processor-net
      - ls_ls-net
    volumes:
      - mysql-data:/var/lib/mysql

#  debug-container:
#    image: mikesir87/aws-cli:latest
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager
#    networks:
#      - image-processor-net
#      - ls_ls-net
#    environment:
#      AWS_ACCESS_KEY_ID: 'foo'
#      AWS_SECRET_ACCESS_KEY: 'bar'
#    command: aws --endpoint=http://s3:4572 s3 mb s3://test-bucket