version: '3.7'

networks:
  ls-net:
    driver: overlay
    attachable: true

services:
  s3:
    image: sridharangopal/localstack-rpi:latest
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3
      - START_WEB=0
    networks: 
      - ls-net
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role != manager
  
  sns:
    image: sridharangopal/localstack-rpi:latest
    ports:
      - "4575:4575"
    environment:
      - SERVICES=sns
      - START_WEB=0
    networks: 
      - ls-net
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role != manager

  sqs:
    image: sridharangopal/localstack-rpi:latest
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - START_WEB=0
    networks: 
      - ls-net
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role != manager