version: '3.7'

networks:
  ls-net:
    driver: overlay
    attachable: true

services:
  s3:
    image: localstack/localstack
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3
      - START_WEB=0
    networks:
      - ls-net

  sns:
    image: localstack/localstack
    ports:
      - "4575:4575"
    environment:
      - SERVICES=sns
      - START_WEB=0
    networks:
      - ls-net

  sqs:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - START_WEB=0
    networks:
      - ls-net